sudo: false
language: node_js
node_js:
  - "lts/*"
  - "9"
  - "10"
matrix:
  include:
    - node_js: "lts/*"
      env: TEST_SUITE=standard
env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
