sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
env:
  - TEST_SUITE=unit
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=standard
script: npm run-script $TEST_SUITE
